Puppet::Type.newtype(:apt_auto_pin) do
  @doc = <<-EOD
Create apt pin files for all packages that have a version specified.
Ideally we would create apt::pin resources for instead of plain files,
but that would require compiling those defined types which we can't do
at this stage.
EOD

  newparam(:title) do
    isnamevar
  end

  newparam(:priority) do
    munge do |value|
      Integer(value)
    end

    defaultto 1000
  end

  def generate
    catalog.resources.find_all { |res| res.type == :package }
      .reject { |res| res[:provider] != 'apt' }
      .reject { |res| ['absent', 'present', 'purged', 'latest', 'installed'].include? res[:ensure] }
      .map do |resource|

      Puppet::Type.type(:file).new({
        path: "/etc/apt/conf.d/apt_auto_pin_#{resource[:name]}.pref",
        ensure: 'file',
        content: <<-EOT
Explanation: Generated by Puppet apt_auto_pin
Package: #{resource[:name]}
Pin: version #{resource[:ensure]}
Pin-Priority: #{self[:priority]}
EOT
      })
    end
  end
end
